name: CI

on:
  workflow_dispatch:

jobs:
  start-rdp:
    runs-on: windows-latest  

    steps:
      - name: install ngrok
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user user pass123! /add
          net localgroup Administrators user /add

      - name: try
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip -DestinationPath .
          ./ngrok.exe authtoken 2tWqdFk1HJ7f9TaLBqVReUm6TJ0_4xH9p2rJCRBhyaoCSS1de
          ./ngrok.exe tcp 3389
